version: '3.8'

services:
  llm-webui:
    build: .
    container_name: llm-webui-container
    ports:
      - "4444:22"
      - "8000:8000"
      - "27015:27015"
    environment:
      - OPENAI_API_BASE_URL=http://localhost:8000/v1
      - OPENAI_API_KEY=sk-fake-key
      - PORT=27015
      - DATA_DIR=/app/open-webui-data
      - VLLM_HOST=0.0.0.0
      - VLLM_PORT=8000
      - VLLM_GPU_MEMORY_UTILIZATION=0.85
      - VLLM_MODEL=deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
      - S6_LOGGING=1
      - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
    volumes:
      - ./data:/app/open-webui-data
      - ./hf-cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true